# Generated by Django 6.1.1 on 2026-09-21 11:41

import django.db.models.deletion
import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orignal_url', models.URLField(max_length=2048)),
                ('short_code', models.CharField(db_index=True, default=shortener.models.generate_short_code, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClickAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referrer', models.URLField(blank=True, default='', max_length=2048)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='shortener.shorturl')),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
    ]
