# Generated by Django 6.1.1 on 2026-09-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='orignal_url',
            new_name='original_url',
        ),
    ]
