# Generated by Django 6.1.1 on 2026-09-21 14:32

import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_rename_orignal_url_shorturl_original_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_code',
            field=models.CharField(db_index=True, default=shortener.models.generate_short_code, max_length=6, unique=True),
        ),
        migrations.AddIndex(
            model_name='clickanalytics',
            index=models.Index(fields=['short_url', '-clicked_at'], name='shortener_c_short_u_e9918c_idx'),
        ),
    ]
