# Generated by Django 6.1.1 on 2026-09-24 08:56

from django.db import migrations, models
from django.db.models import Count


def deactivate_duplicate_active_urls(apps, schema_editor):
    short_url_model = apps.get_model('shortener', 'ShortURL')
    duplicate_urls = (
        short_url_model.objects
        .filter(is_active=True)
        .values('original_url')
        .annotate(total=Count('id'))
        .filter(total__gt=1)
    )

    for duplicate in duplicate_urls:
        duplicate_links = short_url_model.objects.filter(
            original_url=duplicate['original_url'],
            is_active=True,
        ).order_by('created_at', 'id')
        for duplicate_link in duplicate_links[1:]:
            short_url_model.objects.filter(pk=duplicate_link.pk).update(
                is_active=False,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_alter_clickanalytics_id_alter_shorturl_id'),
    ]

    operations = [
        migrations.RunPython(
            deactivate_duplicate_active_urls,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='shorturl',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('original_url',), name='unique_active_original_url'),
        ),
    ]
